### ISSUE TITLE
Is it supported for rails 5?

### ISSUE THREAD

**Issue by marvindanig** [indirect/haml-rails#112]
We're using haml-rails as one of the dependencies on our rails4 application so first thing first -- a very big thanks to you for sharing this beautiful gem with all. Since we're considering an upgrade to rails5 in the near term, I wonder if this gem would be supported for rails 5 or not?

**Comment by doits** [comment]
I've been using this gem with the Rails `5.0.0.rcX` versions successfully (because `5.0.0.rcX < 5.0`).

But now it prevents me to use just released Rails 5.0 version. If there aren't any failures maybe simply raise the bar to `< 5.1.x`? (Afaik this would exclude beta and rc versions of `5.1`, too, like I think what is meant to be.)

**Comment by syguer** [comment]
For now, specs are passed on travis 😄 
If you find some issue, create issue again!
